# Generated by Django 5.1 on 2026-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_remove_booktable_items_bookingitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktable",
            name="items",
            field=models.ManyToManyField(
                through="base_app.BookingItem", to="base_app.items"
            ),
        ),
    ]
