# Generated by Django 5.1 on 2026-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0004_booktable_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktable",
            name="payment_status",
            field=models.CharField(default="Unpaid", max_length=20),
        ),
        migrations.AddField(
            model_name="booktable",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
