# Generated by Django 5.1 on 2026-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0005_booktable_payment_status_booktable_razorpay_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktable",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
